"""add path to ads

Revision ID: 8eaac05198f4
Revises: 94c8afe44c51
Create Date: 2026-08-02 08:10:45.775804

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8eaac05198f4"
down_revision: str | Sequence[str] | None = "94c8afe44c51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ads", sa.Column("path", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ads", "path")
    # ### end Alembic commands ###
