"""create ads ad_metrics ad_comments tables

Revision ID: 94c8afe44c51
Revises:
Create Date: 2026-08-02 07:46:04.394103

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94c8afe44c51"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ads",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("ad_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("image", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ad_id"),
    )
    op.create_table(
        "ad_comments",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ad_id", sa.Text(), nullable=False),
        sa.Column(
            "platform",
            postgresql.ENUM("Google", "Meta", "LinkedIn", name="ad_platform"),
            nullable=False,
        ),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ad_id"], ["ads.ad_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ad_comments_ad_id", "ad_comments", ["ad_id"], unique=False)
    op.create_index("idx_ad_comments_date", "ad_comments", ["date"], unique=False)
    op.create_table(
        "ad_metrics",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ad_id", sa.Text(), nullable=False),
        sa.Column(
            "platform",
            postgresql.ENUM("Google", "Meta", "LinkedIn", name="ad_platform"),
            nullable=False,
        ),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("engagements", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("clicks >= 0", name="ad_metrics_clicks_check"),
        sa.CheckConstraint("engagements >= 0", name="ad_metrics_engagements_check"),
        sa.CheckConstraint("impressions >= 0", name="ad_metrics_impressions_check"),
        sa.ForeignKeyConstraint(["ad_id"], ["ads.ad_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "ad_id", "platform"),
    )
    op.create_index("idx_ad_metrics_ad_date", "ad_metrics", ["ad_id", "date"], unique=False)
    op.create_index("idx_ad_metrics_ad_id", "ad_metrics", ["ad_id"], unique=False)
    op.create_index("idx_ad_metrics_date", "ad_metrics", ["date"], unique=False)
    op.create_index("idx_ad_metrics_platform", "ad_metrics", ["platform"], unique=False)
    op.create_index(
        "idx_ad_metrics_platform_date", "ad_metrics", ["platform", "date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ad_metrics_platform_date", table_name="ad_metrics")
    op.drop_index("idx_ad_metrics_platform", table_name="ad_metrics")
    op.drop_index("idx_ad_metrics_date", table_name="ad_metrics")
    op.drop_index("idx_ad_metrics_ad_id", table_name="ad_metrics")
    op.drop_index("idx_ad_metrics_ad_date", table_name="ad_metrics")
    op.drop_table("ad_metrics")
    op.drop_index("idx_ad_comments_date", table_name="ad_comments")
    op.drop_index("idx_ad_comments_ad_id", table_name="ad_comments")
    op.drop_table("ad_comments")
    op.drop_table("ads")
    # ### end Alembic commands ###
    postgresql.ENUM(name="ad_platform").drop(op.get_bind(), checkfirst=True)
